# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_date', models.DateTimeField()),
                ('challengee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_challengee', to=settings.AUTH_USER_MODEL)),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_contender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contender_score', models.IntegerField()),
                ('challengee_score', models.IntegerField()),
                ('game_data', models.DateField()),
                ('challengee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_challengee', to=settings.AUTH_USER_MODEL)),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_contender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
