# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20171116_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='challengee',
        ),
        migrations.RemoveField(
            model_name='game',
            name='contender',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Challenge'),
        ),
    ]
