# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20171116_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='challenge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Challenge'),
        ),
    ]
