# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_auto_20171116_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challengee_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='contender_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
