# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20171116_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='game_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
