# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_challenge_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='game_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
