# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
