# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0011_challenge_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResultValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField()),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Challenge')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='trend',
            field=models.IntegerField(default=0),
        ),
    ]
