# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0012_auto_20171119_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresultvalidation',
            old_name='id',
            new_name='token',
        ),
    ]
