# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0014_gameresultvalidation_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='game_reported',
            field=models.BooleanField(default=True),
        ),
    ]
