# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0015_challenge_game_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='game_reported',
            field=models.BooleanField(),
        ),
    ]
